package chen.easyview.greendao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoBeanDaoConfig;

    private final TodoBeanDao todoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoBeanDaoConfig = daoConfigMap.get(TodoBeanDao.class).clone();
        todoBeanDaoConfig.initIdentityScope(type);

        todoBeanDao = new TodoBeanDao(todoBeanDaoConfig, this);

        registerDao(TodoBean.class, todoBeanDao);
    }
    
    public void clear() {
        todoBeanDaoConfig.clearIdentityScope();
    }

    public TodoBeanDao getTodoBeanDao() {
        return todoBeanDao;
    }

}
